packages:
  - apps/*
catalog:
  '@bybrave/proper-lockfile2': 5.0.0
  '@types/node': 22.17.1
  '@typescript/native-preview': 7.0.0-dev.20260707.2
  cron-parser: 5.10.0
  incur: 0.5.1
  jsonc-parser: 3.3.1
  listr2: 11.1.0
  oxfmt: 0.65.0
  oxlint: 1.80.0
  pino: 10.3.1
  plist: 5.0.0
  table: 6.9.0
  tsx: 4.23.13
allowBuilds:
  esbuild: true
