import type { Dependency } from '@wendellhu/redi'

import {
  IAddRepoMirrorService,
  IAddTaskTemplateService,
  IAddTaskRepoMirrorsService,
  IConcurrencyService,
  IDoctorRepoMirrorService,
  IFetchRepoMirrorService,
  IFetchTaskService,
  IFileSystemService,
  IGetRepoMirrorLogsService,
  IGetRepoMirrorPathService,
  IGitCommandService,
  IGitService,
  IGitsPathService,
  IGitsPersistenceService,
  IInitializeTaskService,
  IInstallTaskService,
  IListRepoMirrorService,
  IListTaskTemplateService,
  IProcessService,
  IPushTaskService,
  IRemoveRepoMirrorService,
  IRemoveTaskTemplateService,
  IRenameTaskTemplateService,
  IRepoMirrorConfigurationService,
  IRepoMirrorDependencyService,
  IRepoMirrorGitService,
  IRepoMirrorLockService,
  IRepoMirrorLoggerService,
  IRepoMirrorSchedulerService,
  IRepoMirrorStoreService,
  IRepoMirrorViewService,
  IResolveRepoMirrorService,
  ISetRepoMirrorService,
  IStableRunnerInstaller,
  IStatusTaskService,
  ISwitchTaskService,
  ITaskConfigurationService,
  ITaskDirectoryMaterializationService,
  ITaskDirectorySourcePlanService,
  ITaskRootService,
  ITaskScaffoldService,
  ITaskTemplateLockService,
  ITaskTemplateSnapshotService,
  ITaskTemplateStoreService,
  IUpdateTaskTemplateService,
  IUninstallService,
} from './contract/index'
import {
  AddRepoMirrorService,
  AddTaskTemplateService,
  AddTaskRepoMirrorsService,
  DoctorRepoMirrorService,
  FetchRepoMirrorService,
  FetchTaskService,
  GetRepoMirrorLogsService,
  GetRepoMirrorPathService,
  GitsPersistenceService,
  InitializeTaskService,
  InstallTaskService,
  ListRepoMirrorService,
  ListTaskTemplateService,
  PushTaskService,
  RemoveRepoMirrorService,
  RemoveTaskTemplateService,
  RenameTaskTemplateService,
  RepoMirrorConfigurationService,
  RepoMirrorDependencyService,
  RepoMirrorGitService,
  RepoMirrorLockService,
  RepoMirrorLoggerService,
  RepoMirrorSchedulerService,
  RepoMirrorStoreService,
  RepoMirrorViewService,
  ResolveRepoMirrorService,
  SetRepoMirrorService,
  StableRunnerInstaller,
  StatusTaskService,
  SwitchTaskService,
  TaskConfigurationService,
  TaskDirectoryMaterializationService,
  TaskDirectorySourcePlanService,
  TaskRootService,
  TaskScaffoldService,
  TaskTemplateLockService,
  TaskTemplateSnapshotService,
  TaskTemplateStoreService,
  UninstallService,
  UpdateTaskTemplateService,
} from './module/index'
import {
  ConcurrencyService,
  FileSystemService,
  GitCommandService,
  GitService,
  GitsPathService,
  ProcessService,
} from './service/index'

export const coreDependencies: Dependency[] = [
  [IConcurrencyService, { useClass: ConcurrencyService }],
  [IFileSystemService, { useClass: FileSystemService }],
  [IGitCommandService, { useClass: GitCommandService }],
  [IGitService, { useClass: GitService }],
  [IGitsPathService, { useClass: GitsPathService }],
  [IProcessService, { useClass: ProcessService }],

  [
    IRepoMirrorConfigurationService,
    { useClass: RepoMirrorConfigurationService },
  ],
  [IRepoMirrorDependencyService, { useClass: RepoMirrorDependencyService }],
  [IRepoMirrorGitService, { useClass: RepoMirrorGitService }],
  [IRepoMirrorLockService, { useClass: RepoMirrorLockService }],
  [IRepoMirrorLoggerService, { useClass: RepoMirrorLoggerService }],
  [IRepoMirrorSchedulerService, { useClass: RepoMirrorSchedulerService }],
  [IRepoMirrorStoreService, { useClass: RepoMirrorStoreService }],
  [IRepoMirrorViewService, { useClass: RepoMirrorViewService }],
  [IStableRunnerInstaller, { useClass: StableRunnerInstaller }],
  [IResolveRepoMirrorService, { useClass: ResolveRepoMirrorService }],
  [IAddRepoMirrorService, { useClass: AddRepoMirrorService }],
  [IDoctorRepoMirrorService, { useClass: DoctorRepoMirrorService }],
  [IFetchRepoMirrorService, { useClass: FetchRepoMirrorService }],
  [IGetRepoMirrorLogsService, { useClass: GetRepoMirrorLogsService }],
  [IGetRepoMirrorPathService, { useClass: GetRepoMirrorPathService }],
  [IListRepoMirrorService, { useClass: ListRepoMirrorService }],
  [IRemoveRepoMirrorService, { useClass: RemoveRepoMirrorService }],
  [ISetRepoMirrorService, { useClass: SetRepoMirrorService }],

  [ITaskConfigurationService, { useClass: TaskConfigurationService }],
  [
    ITaskDirectoryMaterializationService,
    { useClass: TaskDirectoryMaterializationService },
  ],
  [
    ITaskDirectorySourcePlanService,
    { useClass: TaskDirectorySourcePlanService },
  ],
  [ITaskRootService, { useClass: TaskRootService }],
  [ITaskScaffoldService, { useClass: TaskScaffoldService }],
  [ITaskTemplateLockService, { useClass: TaskTemplateLockService }],
  [ITaskTemplateSnapshotService, { useClass: TaskTemplateSnapshotService }],
  [ITaskTemplateStoreService, { useClass: TaskTemplateStoreService }],
  [IAddTaskTemplateService, { useClass: AddTaskTemplateService }],
  [IListTaskTemplateService, { useClass: ListTaskTemplateService }],
  [IRemoveTaskTemplateService, { useClass: RemoveTaskTemplateService }],
  [IRenameTaskTemplateService, { useClass: RenameTaskTemplateService }],
  [IUpdateTaskTemplateService, { useClass: UpdateTaskTemplateService }],
  [IAddTaskRepoMirrorsService, { useClass: AddTaskRepoMirrorsService }],
  [IFetchTaskService, { useClass: FetchTaskService }],
  [IInitializeTaskService, { useClass: InitializeTaskService }],
  [IInstallTaskService, { useClass: InstallTaskService }],
  [IPushTaskService, { useClass: PushTaskService }],
  [IStatusTaskService, { useClass: StatusTaskService }],
  [ISwitchTaskService, { useClass: SwitchTaskService }],

  [IGitsPersistenceService, { useClass: GitsPersistenceService }],
  [IUninstallService, { useClass: UninstallService }],
]
